//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSA_Application {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class textResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal textResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSA_Application.textResource", typeof(textResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [입구 영역]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CV_INPUT_AREA {
            get {
                return ResourceManager.GetString("CV_INPUT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [입구 버퍼]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CV_INPUT_BUFFER {
            get {
                return ResourceManager.GetString("CV_INPUT_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [출구 영역]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CV_OUTPUT_AREA {
            get {
                return ResourceManager.GetString("CV_OUTPUT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [작업 영역]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CV_WORK_AREA {
            get {
                return ResourceManager.GetString("CV_WORK_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 [{0}] (으)로 Log-In 했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_LOGIN {
            get {
                return ResourceManager.GetString("LOG_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset Data를 초기화 할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CAL_INIT_OFFSET {
            get {
                return ResourceManager.GetString("MB_CAL_INIT_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지그를 준비해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CAL_INSERT_JIG {
            get {
                return ResourceManager.GetString("MB_CAL_INSERT_JIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트레이를 레일 위에 올려 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CAL_INSERT_TRAY {
            get {
                return ResourceManager.GetString("MB_CAL_INSERT_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지그를 제거해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CAL_REMOVE_JIG {
            get {
                return ResourceManager.GetString("MB_CAL_REMOVE_JIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트레이를 제거해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CAL_REMOVE_TRAY {
            get {
                return ResourceManager.GetString("MB_CAL_REMOVE_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨베어를 초기화 할 수 없습니다.
        ///트레이가 [{0}] 에 존재 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_CANNOT_INITIALIZE {
            get {
                return ResourceManager.GetString("MB_CV_CANNOT_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 센서가 감지되고 있습니다.
        ///트레이를 손으로 제거하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_EXIST {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [입구]와 [버퍼] 센서가 동시에 감지되었습니다.
        ///상태 확인후 다시 시도하세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_EXIST_SENSOR {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_EXIST_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트레이 로딩 정보를 선택해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_LOADING_INFO {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_LOADING_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 트레이 정보를 삭제할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_REJECT {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   트레이가 검사되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_REV_CHECK_ERROR {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_REV_CHECK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사시간 : {0}[us]\n검사결과 : {1}[mm]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_REV_CHECK_RESULT {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_REV_CHECK_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨베이어 상에 트레이가 감지되지 않았습니다.
        ///이전 장비로부터 이송을 시도할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_CV_TRAY_TRANSFER {
            get {
                return ResourceManager.GetString("MB_CV_TRAY_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 시작 날짜가 검색 마지막 날짜보다 큽니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ERROR_REPORT_DATE_ERROR {
            get {
                return ResourceManager.GetString("MB_ERROR_REPORT_DATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메인 공압이 정상상태인지 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_CHECK_AIR {
            get {
                return ResourceManager.GetString("MB_ETC_CHECK_AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOTOR [ON]상태인지 검사하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_CHECK_SERVO {
            get {
                return ResourceManager.GetString("MB_ETC_CHECK_SERVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진공압(VACUUM)이 정상상태인지 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_CHECK_VAC {
            get {
                return ResourceManager.GetString("MB_ETC_CHECK_VAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 통신 에러 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_COMM_ERROR {
            get {
                return ResourceManager.GetString("MB_ETC_COMM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_EXIT_SW {
            get {
                return ResourceManager.GetString("MB_ETC_EXIT_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 읽기를 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_FILE_LOAD_FAIL {
            get {
                return ResourceManager.GetString("MB_ETC_FILE_LOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 읽기를 성공했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_FILE_LOAD_OK {
            get {
                return ResourceManager.GetString("MB_ETC_FILE_LOAD_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 파일이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("MB_ETC_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 저장에 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_FILE_SAVE_FAIL {
            get {
                return ResourceManager.GetString("MB_ETC_FILE_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 를 정상적으로 저장했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_FILE_SAVE_OK {
            get {
                return ResourceManager.GetString("MB_ETC_FILE_SAVE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 파라미터를 적용할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_PARA_SAVE {
            get {
                return ResourceManager.GetString("MB_ETC_PARA_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 파라미터를 적용한 뒤 종료할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_PARA_SAVE_BEFORE_EXIT {
            get {
                return ResourceManager.GetString("MB_ETC_PARA_SAVE_BEFORE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 파라미터를 적용한 뒤 시작할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_PARA_SAVE_BEFORE_START {
            get {
                return ResourceManager.GetString("MB_ETC_PARA_SAVE_BEFORE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 재시작 후 적용됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_SW_RESTART {
            get {
                return ResourceManager.GetString("MB_ETC_SW_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 데이터가 선택된 값으로 변경됩니다. 계속 진행할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_UPDATE_TRAY_INFO_ALL {
            get {
                return ResourceManager.GetString("MB_ETC_UPDATE_TRAY_INFO_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정말로 자동보정값을 초기화 할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_PICK_INIT_AUTO_TRACK {
            get {
                return ResourceManager.GetString("MB_HD_PICK_INIT_AUTO_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_PICK_INIT_FINISH {
            get {
                return ResourceManager.GetString("MB_HD_PICK_INIT_FINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 Pick Offset X,Y,Z 값은 초기화 됩니다.
        ///계속 진행할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_PICK_INIT_OFFSET_XYZ {
            get {
                return ResourceManager.GetString("MB_HD_PICK_INIT_OFFSET_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 Pick Offset Z 값은 초기화 됩니다.
        ///계속 진행할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_PICK_INIT_OFFSET_Z {
            get {
                return ResourceManager.GetString("MB_HD_PICK_INIT_OFFSET_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press 모드용 TMS 파일이 생성되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_PRESS_CREATE_TMS {
            get {
                return ResourceManager.GetString("MB_HD_PRESS_CREATE_TMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 의 원점을 새로 잡아 주새요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_REQ_INIT {
            get {
                return ResourceManager.GetString("MB_REQ_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 의 사용유무가 OFF 되어 있어서
        ///사용할 수 없습니다.
        ///사용하려면 사용유무를 ON 해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_SF_ONOFF {
            get {
                return ResourceManager.GetString("MB_SF_ONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자[{0}]가 추가되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_ADD_ACCOUNT {
            get {
                return ResourceManager.GetString("MB_USER_ADD_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password 를 다시 한번 입력해 주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_CONFIRM_PW {
            get {
                return ResourceManager.GetString("MB_USER_CONFIRM_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자[{0}]가 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("MB_USER_DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 Password 를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_INPUT_NEW_PW {
            get {
                return ResourceManager.GetString("MB_USER_INPUT_NEW_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자[{0}] Password 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_INPUT_PW {
            get {
                return ResourceManager.GetString("MB_USER_INPUT_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   먼저 Log-In을 하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_LOG_IN_ACCOUNT {
            get {
                return ResourceManager.GetString("MB_USER_LOG_IN_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 [{0}]로 Log-In했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_LOGGED_IN_ACCOUNT {
            get {
                return ResourceManager.GetString("MB_USER_LOGGED_IN_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 [{0}]가 Log-Out했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_LOGOUT {
            get {
                return ResourceManager.GetString("MB_USER_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Master Password가 정확하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_MASTER_PW_FAIL {
            get {
                return ResourceManager.GetString("MB_USER_MASTER_PW_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름은 최소 2글자이상이어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_NAME_COUNT_FAIL {
            get {
                return ResourceManager.GetString("MB_USER_NAME_COUNT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 사용자 이름이 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_NAME_DUPLICATE_FAIL {
            get {
                return ResourceManager.GetString("MB_USER_NAME_DUPLICATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 이름이 목록에 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_NOT_EXIST_NAME {
            get {
                return ResourceManager.GetString("MB_USER_NOT_EXIST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password는 최소 2글자이상이어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_PW_COUNT_FAIL {
            get {
                return ResourceManager.GetString("MB_USER_PW_COUNT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password가 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_PW_FAIL {
            get {
                return ResourceManager.GetString("MB_USER_PW_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자를 먼저 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_USER_SELECT_ACCOUNT {
            get {
                return ResourceManager.GetString("MB_USER_SELECT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부가정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_ADDITIONAL_INFORMATION {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_ADDITIONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   축이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_AXIS_NAME {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_AXIS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러내용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_CONTENTS_OF_ERROR {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_CONTENTS_OF_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_ERRORCODE {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_ERRORCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발생시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_OCCURRED_TIME {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_OCCURRED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조치사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_SOLUTION {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발생원인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_SOURCE {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SW모듈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_ERROR_REPORT_SW_MODULE {
            get {
                return ResourceManager.GetString("TB_ERROR_REPORT_SW_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 점검이 필요합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_SYSTEM_CHECK_FAIL {
            get {
                return ResourceManager.GetString("TB_SYSTEM_CHECK_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료하려면 프로텍 로그를 더블클릭하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_SYSTEM_CHECK_FAIL_EXIT {
            get {
                return ResourceManager.GetString("TB_SYSTEM_CHECK_FAIL_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템이 정상 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TB_SYSTEM_CHECK_OK {
            get {
                return ResourceManager.GetString("TB_SYSTEM_CHECK_OK", resourceCulture);
            }
        }
    }
}
