//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSA_SystemLibrary {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class textResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal textResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSA_SystemLibrary.textResource", typeof(textResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [Center Right : {0}] 의 [Button : {1}] 이(가) 클릭되었습니다. (by {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_CLICK_BUTTON {
            get {
                return ResourceManager.GetString("LOG_CLICK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Button : {0}] 이(가) 클릭되었습니다. (by {1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_CLICK_BUTTON_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_CLICK_BUTTON_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [I/O Menu : {0}] 의 [Button : {1}] 이(가) 클릭되었습니다. (by {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_CLICK_BUTTON_IO {
            get {
                return ResourceManager.GetString("LOG_CLICK_BUTTON_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Center Right : {0}] 의 [{1}] 이(가) 클릭되었습니다. (by {2})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_CLICK_TAG {
            get {
                return ResourceManager.GetString("LOG_CLICK_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Force 차이값이 너무 크기 때문에 보정값을 0으로 재 설정 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_DEBUG_HD_FORCE_TRACKING_INIT {
            get {
                return ResourceManager.GetString("LOG_DEBUG_HD_FORCE_TRACKING_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   판넬의 {0} 버튼이 눌렸습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_DEBUG_PUSHED_BTN {
            get {
                return ResourceManager.GetString("LOG_DEBUG_PUSHED_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 의 자재가 모두 소진되어 Down 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_DEBUG_SF_READY_DOWN {
            get {
                return ResourceManager.GetString("LOG_DEBUG_SF_READY_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Ready 상태이므로 Up 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_DEBUG_SF_READY_UP {
            get {
                return ResourceManager.GetString("LOG_DEBUG_SF_READY_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPC 폴더에 있는 {0} 파일을 복사 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_ERROR_MPC_FAILED_COPY_FILE {
            get {
                return ResourceManager.GetString("LOG_ERROR_MPC_FAILED_COPY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pedestal 이 Error 상태이기 때문에 준비동작을 완료할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_ERROR_PEDESTAL_NOT_READY {
            get {
                return ResourceManager.GetString("LOG_ERROR_PEDESTAL_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool 평탄도[{0}] - Touch Probe Value : {1} [um]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_TRACE_HD_TOOL_FLATNESS {
            get {
                return ResourceManager.GetString("LOG_TRACE_HD_TOOL_FLATNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool 평탄도 Max : {0}, Min : {1}, Max Diff : {2} [um]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_TRACE_HD_TOOL_FLATNESS_RESULT {
            get {
                return ResourceManager.GetString("LOG_TRACE_HD_TOOL_FLATNESS_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pedestal 평탄도[{0}] - Laser Value : {1} (um)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_TRACE_PD_FLATNESS {
            get {
                return ResourceManager.GetString("LOG_TRACE_PD_FLATNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pedestal 평탄도 Max : {0}, Min : {1}, Max Diff : {2} [um]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG_TRACE_PD_FLATNESS_RESULT {
            get {
                return ResourceManager.GetString("LOG_TRACE_PD_FLATNESS_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 통신 에러 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_ETC_COMM_ERROR {
            get {
                return ResourceManager.GetString("MB_ETC_COMM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : Attach 를 진행 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_ATTACH {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_ATTACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : Double Check 검사 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_DOUBLE_DET {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_DOUBLE_DET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : 자재 방향을 검사 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_ISP_ORIENTATION {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_ISP_ORIENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : 기울기 측정을 진행 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_ISP_TILT {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_ISP_TILT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes : 트레이 맵 정보 이용
        ///No: 매뉴얼 지정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_LOAD_TMS {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_LOAD_TMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : Tool 을 Pick 위치로 이동 합니다.
        ///({0} 위치)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_MOVE_PICK {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_MOVE_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   두 번째 서치 위치로 이동 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_MOVE_S2 {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_MOVE_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대기 위치로 이동 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_MOVE_STANDBY {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_MOVE_STANDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : HeatSlug 검사위치로 이동 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_MOVE_ULC {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_MOVE_ULC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자재를 버리지 말고 검사 위치로 이동 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_NOWASTE {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_NOWASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : 자재 얼라인을 진행 합니다.
        ///얼라인 진행 후 첫 번째 서치 위치로 이동 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_PCB_ALIGN {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_PCB_ALIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : Pick Down 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_PICK_DOWN {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_PICK_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : Stack Feeder 를 Up 시킵니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_REQ_SF_UP {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_REQ_SF_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : 자재를 흡착 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_SUC_HS {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_SUC_HS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 : Vibration Mode 시작 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_VIB {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_VIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자재를 버릴까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_HD_CYCLE_WASTE {
            get {
                return ResourceManager.GetString("MB_HD_CYCLE_WASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tube가 활성화 되어 있지 않습니다.
        ///장비 패널의 Magazine Button 을 누르거나
        ///Edit 창을 열어서 Tube를 활성화 시키십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MB_SF_TUBE_ERROR {
            get {
                return ResourceManager.GetString("MB_SF_TUBE_ERROR", resourceCulture);
            }
        }
    }
}
